### ISSUE TITLE
报错，缺文件，我看输入需求没有这个要求，是代码中哪个文件可以生成这个吗，请帮我解决，谢谢

### ISSUE THREAD

**Issue by yanglogjms** [mmlab-sigs/SizeGS#1]
Traceback (most recent call last):
  File "meson.py", line 788, in <module>
    args.load_iter, wandb, logger)
  File "meson.py", line 161, in training
    scene = Scene(dataset, gaussians, load_iteration=load_iteration, shuffle=False)
  File "/home/yanglong/projects/sizegs/scene/__init__.py", line 112, in __init__
    "iteration_" + str(self.loaded_iter)))
  File "/home/yanglong/projects/sizegs/scene/gaussian_model.py", line 1405, in load_mlp_checkpoints
    self.mlp_opacity = torch.jit.load(os.path.join(path, 'opacity_mlp.pt')).cuda()
  File "/opt/miniconda3/envs/sizegs/lib/python3.7/site-packages/torch/jit/_serialization.py", line 152, in load
    raise ValueError("The provided filename {} does not exist".format(f))  # type: ignore[str-bytes-safe]
ValueError: The provided filename /home/3030303/projects/sizegs/outputs/360_v2/scence1/baseline/point_cloud/iteration_30000/opacity_mlp.pt does not exist

**Comment by yanglogjms** [comment]
这个问题解决了，然后我又碰到输出没有ply文件，将scene.save_compressed改成scene.save，但是最后输出的ply文件没有颜色是为什么，可以帮我解决一下吗，万分感谢

**Comment by ShuzhaoXie** [comment]
@2003jiahang 辛苦佳航帮忙解答下

**Comment by ShuzhaoXie** [comment]
如果想存一个3DGS文件，可以在[这个函数](https://github.com/mmlab-sigs/SizeGS/blob/bf141cab14ad2fdd64ea65dcf872d11df7f87ce0/gaussian_renderer/__init__.py#L128)附近保存一下ply，当然，这里只有rgb。

总之，我们这里存下来的是个ScffoldGS文件，具体请参考ScaffoldGS的论文：https://arxiv.org/abs/2312.00109

@2003jiahang 负责大部分代码的编写，如有需要可以再补充一些。

**Comment by 2003jiahang** [comment]
正如 @ShuzhaoXie 所说，我们保存的是Scaffold形式的文件，并且在gaussians.save_compressed方法中我们将保存下来的文件压缩为了.zip形式。最后保存的结果如下：
```
outputs/
├── dataset_name
│   ├── scene/
│   │   ├── sizegs/
│   │       ├── (date "+%Y-%m-%d_%H:%M:%S")/
|   |             ├── zip/
|   |                 ├──bin.zip/
|   |                 └──bin/
|   |                    ├──color_mlp.pt
|   |                    ├──cov_mlp.pt
|   |                    ├──fe.npz
|   |                    ├──oct.npz
|   |                    └──opacity_mlp.pt

```
